#pragma once

// Warning! This file is @generated by cbindgen. Do not modify.

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct {
  uintptr_t data;
} HeapObject;

typedef uintptr_t Object;

typedef struct {
  HeapObject obj;
  int64_t value;
} IntObject;

extern const HeapObject *twb_as_heap_object(Object obj);

extern const IntObject *twb_as_int_object(Object obj);

extern void twb_print(Object obj);
